# Generated by Django 3.1.2 on 2020-10-10 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20201010_1831'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
